<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bot">
  <xacro:property name="length" value="0.93" />
  <xacro:property name="breadth" value="0.83" />
  <xacro:property name="width" value="0.315" />
  <xacro:property name="wheel_thickness" value="0.05" />
  <xacro:property name="wheel_radius" value="0.12" />

  <xacro:property name="caster_scale" value="2" />
  <xacro:property name="caster_pos_x" value="${length/2}" />
  <xacro:property name="caster_pos_y" value="0.0" />
  <xacro:property name="caster_pos_z" value="${-width/2 + 0.015}" />
  <xacro:property name="camera_link" value="0.001" />
  <xacro:include filename="robot_control.xacro" /> 
  <xacro:include filename="robot_camera_autonav.xacro" />
  <xacro:include filename="robot_lidar.xacro" />
  <xacro:include filename="robot_gps.xacro" /> 

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.3" ixy="0.0" ixz="0.0"
	  iyy="1.3" iyz="0.0"
	  izz="1.3"/>
    </inertial>
  </link>

  <link name="chassis">
    <collision>
    <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <geometry>
	      <box size="${length} ${breadth} ${width}"/>
      </geometry>
    </collision>

    <visual>
	    <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${length} ${breadth} ${width}"/>
      </geometry>
    </visual>

    <inertial>
	    <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia
	  ixx="0.67" ixy="0.0" ixz="0.0"
	  iyy="0.4" iyz="0.0"
	  izz="0.8"/>
    </inertial>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    <limit effort="1000000" velocity="10000000"/>
  </joint>

  <link name="wheel">
    <collision>
	    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.0072" ixy="0.0" ixz="0.0"
	  iyy="0.0036" iyz="0.0"
	  izz="0.0036"/>
    </inertial>
  </link>
  <joint name="wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="wheel"/>
    <origin xyz="0 ${breadth/2 + wheel_thickness/2} ${-width/2}" rpy="-1.57 0 0"/>
    <limit effort="1000000" velocity="10000000"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel1">
    <collision>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.0072" ixy="0.0" ixz="0.0" iyy="0.0036" iyz="0.0036"
	  izz="0.1"/>
    </inertial>
  </link>

  <joint name="wheel1_joint" type="continuous">
    <parent link="chassis"/>
    <child link="wheel1"/>
    <origin xyz="0 ${-breadth/2 - wheel_thickness/2} ${-width/2}" rpy="-1.57 0 0"/>
    <limit effort="1000000" velocity="10000000"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="caster_part1">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 -1.57"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caster_base2.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0"  rpy="0 0 -1.57"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caster_base2.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 -1.57"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.000625" ixy="0.0" ixz="0.0"
	  iyy="0.0003125" iyz="0.0"
	  izz="0.0003125"/>
    </inertial>
  </link>
  <link name="caster_wheel1">
    <collision>
    <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caswheel.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caswheel.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.000625" ixy="0.0" ixz="0.0"
	  iyy="0.0003125" iyz="0.0"
	  izz="0.0003125"/>
    </inertial>
  </link>
  <joint name="caster_joint1" type="continuous">
    <parent link="caster_part1"/>
    <child link="caster_wheel1"/>
    <origin xyz="0 0.05 -0.086" rpy="0 0 0"/>
    <limit effort="1000000" velocity="10000000"/>
  </joint>

  <joint name="caster_body_joint1" type="continuous">
    <parent link="chassis"/>
    <child link="caster_part1"/>
    <origin xyz="${-caster_pos_x} ${caster_pos_y} ${caster_pos_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000000" velocity="10000000"/>
  </joint>

  <link name="caster_part">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 -1.57"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caster_base2.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0"  rpy="0 0 -1.57"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caster_base2.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 -1.57"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.000625" ixy="0.0" ixz="0.0"
	  iyy="0.0003125" iyz="0.0"
	  izz="0.0003125"/>
    </inertial>
  </link>
  <link name="caster_wheel">
    <collision>
    <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caswheel.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caswheel.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.000625" ixy="0.0" ixz="0.0"
	  iyy="0.0003125" iyz="0.0"
	  izz="0.0003125"/>
    </inertial>
  </link>
  <joint name="caster_joint" type="continuous">
    <parent link="caster_part"/>
    <child link="caster_wheel"/>
    <origin xyz="0 0.05 -0.086" rpy="0 0 0"/>
    <limit effort="1000000" velocity="10000000"/>
  </joint>

  <joint name="caster_body_joint" type="continuous">
    <parent link="chassis"/>
    <child link="caster_part"/>
    <origin xyz="${caster_pos_x} ${caster_pos_y} ${caster_pos_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000000" velocity="10000000"/>
  </joint>

  <link name="depth_camera_optical_link">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.00000625" ixy="0.0" ixz="0.0"
	  iyy="0.000003125" iyz="0.0"
	  izz="0.000003125"/>
    </inertial>
  </link>

  <link name="depth_camera_link">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.00000625" ixy="0.0" ixz="0.0"
	  iyy="0.000003125" iyz="0.0"
	  izz="0.000003125"/>
    </inertial>
  </link>

  <joint name="depth_camera_joint" type="fixed">
    <parent link="chassis"/>
    <child link="depth_camera_link"/>
    <origin xyz="0.05 0 0.8" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000000" velocity="1000000"/>
  </joint>

   <joint name="transform_correction" type="fixed">
    <parent link="depth_camera_link"/>
    <child link="depth_camera_optical_link"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint> 

  <link name="camera_link">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.00000625" ixy="0.0" ixz="0.0"
	  iyy="0.000003125" iyz="0.0"
	  izz="0.000003125"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="chassis"/>
    <child link="camera_link"/>
    <origin xyz="0 0 0.9" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000000" velocity="1000000"/>
  </joint>

  <link name="lidar_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  <joint name="lidar_joint" type="fixed">
    <parent link="chassis"/>
    <child link="lidar_link"/>
    <origin xyz="0 ${-caster_pos_y/4} 0.45" rpy="0 0 1.57"/>
  </joint> 

  <link name="gps_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  <joint name="gps_joint" type="fixed">
    <parent link="chassis"/>
    <child link="gps_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
</robot>
