<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bot">
  <xacro:property name="caster_z" value="0.02115" />
  <xacro:property name="caster_scale" value="2" />
  <xacro:property name="caster_pos_x" value="-0.175" />
  <xacro:property name="caster_pos_y" value="0.45" />
  <xacro:property name="caster_pos_z" value="0.014" />
  <xacro:property name="camera_link" value="0.001" />
  <xacro:property name="camera_common_radius" value="0.03" />
  <xacro:property name="camera_subtended_angle" value="1.57" />
  <!-- <xacro:include filename="dummy_control.xacro" /> -->
  <xacro:include filename="robot_camera.xacro" />
  <xacro:include filename="robot_lidar.xacro" />
  <xacro:include filename="robot_gps.xacro" />
<material name="white">
		<color rgba="1 1 1 1"/>
</material>

<material name="orange">
		<color rgba="1 0.3 0.1 1"/>
</material>

<material name="blue">
		<color rgba="0.2 0.2 1 1"/>
</material>

<material name="black">
		<color rgba="0 0 0 1"/>
</material>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
		ixx="1.3" ixy="0.0" ixz="0.0"
	  iyy="1.3" iyz="0.0"
	  izz="1.3"/>
    </inertial>
  </link>

	<joint name="chassis_joint" type="fixed">
			<parent link="base_link"/>
			<child link="chassis"/>
			<origin xyz="-0.1 0 0"/>
	</joint>
	<link name="chassis">
			<visual>
					<origin xyz="0.15 0 0.075" rpy="0 0 0"/>
					<geometry>
							<box size="0.3 0.3 0.15"/>
					</geometry>
					<material name="white"/>
			</visual>
	</link>

<!-- LEFT WHEEL -->

	<joint name="left_wheel_joint" type="continuous">
			<parent link="base_link"/>
			<child link="left_wheel"/>
			<origin xyz="0 0.175 0" rpy="-${pi/2} 0 0"/>
			<axis xyz="0 0 1"/>
	</joint>
	<link name="left_wheel">
			<visual>
					<geometry>
							<cylinder length="0.04" radius="0.05" />
					</geometry>
			</visual>
	</link>

<!-- RIGHT WHEEL -->

	<joint name="right_wheel_joint" type="continuous">
			<parent link="base_link"/>
			<child link="right_wheel"/>
			<origin xyz="0 -0.175 0" rpy="${pi/2} 0 0"/>
			<axis xyz="0 0 -1"/>
	</joint>
	<link name="right_wheel">
			<visual>
					<geometry>
							<cylinder length="0.04" radius="0.05" />
					</geometry>
			</visual>
	</link>

  <link name="caster_part">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 -1.57"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caster_base2.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0"  rpy="0 0 -1.57"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caster_base2.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 -1.57"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.000625" ixy="0.0" ixz="0.0"
	  iyy="0.0003125" iyz="0.0"
	  izz="0.0003125"/>
    </inertial>
  </link>
  <link name="caster_wheel">
    <collision>
    <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caswheel.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
      <mesh filename="package://robot_desc/meshes/caswheel.dae" scale="${caster_scale} ${caster_scale} ${caster_scale}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.000625" ixy="0.0" ixz="0.0"
	  iyy="0.0003125" iyz="0.0"
	  izz="0.0003125"/>
    </inertial>
  </link>
  <joint name="caster_joint" type="continuous">
    <parent link="caster_part"/>
    <child link="caster_wheel"/>
    <origin xyz="0 0.05 -0.086" rpy="0 0 0"/>
    <limit effort="1000000" velocity="10000000"/>
  </joint>
  <joint name="caster_body_joint" type="continuous">
    <parent link="chassis"/>
    <child link="caster_part"/>
    <origin xyz="0.24 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000000" velocity="10000000"/>
  </joint>


  <link name="camera_short_link">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.00000625" ixy="0.0" ixz="0.0"
	  iyy="0.000003125" iyz="0.0"
	  izz="0.000003125"/>
    </inertial>
  </link>

  <joint name="camera_short_joint" type="fixed">
    <parent link="chassis"/>
    <child link="camera_short_link"/>
    <origin xyz="${-camera_common_radius*sin(camera_subtended_angle/2)} ${-caster_pos_y/2 + camera_common_radius*cos(camera_subtended_angle/2)} 0.9" rpy="0 0 ${-1.57-camera_subtended_angle/2}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000000" velocity="1000000"/>
  </joint>

  <link name="camera_link">
    <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="0.00000625" ixy="0.0" ixz="0.0"
	  iyy="0.000003125" iyz="0.0"
	  izz="0.000003125"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="chassis"/>
    <child link="camera_link"/>
    <origin xyz="${camera_common_radius*sin(camera_subtended_angle/2)} ${-caster_pos_y/2 + camera_common_radius*cos(camera_subtended_angle/2)} 0.9" rpy="0 0 ${-1.57+camera_subtended_angle/2}"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000000" velocity="1000000"/>
  </joint>

  <link name="lidar_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  <joint name="lidar_joint" type="fixed">
    <parent link="chassis"/>
    <child link="lidar_link"/>
    <origin xyz="0 ${-caster_pos_y/4} 0.45" rpy="0 0 0"/>
  </joint>

  <link name="gps_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>      
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  <joint name="gps_joint" type="fixed">
    <parent link="chassis"/>
    <child link="gps_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
</robot>
